Model:
    dlinear:
        seq_len: 70
        label_len: 35
        pred_len: 35
        num_kernel: 25
        enc_in: 1
        individual: 0
        learning_rate: 0.001
        patience_scheduler: 16
        epochs : 100

    TimesNet:
        task_name: short_term_forecast
        seq_len: 12
        label_len: 12
        pred_len: 12
        e_layers: 2
        embed: timeF
        freq: h
        dropout: 0.1
        top_k: 5
        d_model: 256
        d_ff: 256
        factor: 3
        num_kernels: 6
        output_attention: 0
        distil: 1

    FEDformer:
        task_name: short_term_forecast
        seq_len: 12
        label_len: 12
        pred_len: 12
        e_layers: 2
        d_layers: 1
        num_kernels: 6
        embed: timeF
        freq: h
        dropout: 0.1
        d_model: 512
        d_ff: 2048
        n_heads: 8
        factor: 3
        output_attention: 0
        distil: 1
        activation: gelu
        moving_avg: 25

    Autoformer:
        task_name: short_term_forecast
        seq_len: 12
        label_len: 12
        pred_len: 12
        e_layers: 2
        d_layers: 1
        num_kernels: 6
        embed: timeF
        freq: h
        dropout: 0.1
        d_model: 512
        d_ff: 2048
        n_heads: 8
        factor: 3
        output_attention: 0
        distil: 1
        activation: gelu
        moving_avg: 25

Dataset:
    PEMS03:
        data_filename: ./dataset/PEMS03/PEMS03.npz
        num_of_vertices: 358
        period: 288
        points_per_hour: 12
        num_for_predict: 12
        len_input: 12
        dataset_name: PEMS03
        use_timestamps: False

    PEMS04:
        data_filename: ./dataset/PEMS04/PEMS04.npz
        num_of_vertices: 307
        period: 288
        points_per_hour: 12
        num_for_predict: 12
        len_input: 12
        dataset_name: PEMS04
        use_timestamps: False

    PEMS08:
        data_filename: ./dataset/PEMS08/PEMS08.npz
        num_of_vertices: 170
        period: 288
        points_per_hour: 12
        num_for_predict: 12
        len_input: 12
        dataset_name: PEMS08
        use_timestamps: False

    euma:
        data_filename: ./dataset/euma.csv
        num_of_vertices: 1
        period: 138
        points_per_hour: 6
        num_for_predict: 35
        len_input: 70
        dataset_name: euma
        use_timestamps: False

Attack:
    backtime:
        num_values: 10
        poison_length: 1
        epsilon: 0.1
        batch_size: 40
        learning_rate: 0.0001
        attack_lr: 0.005
        epochs: 100
        warmup: 10
        gpuid: '0'
        surrogate_name: dlinear
        model_name: dlinear
        dataset: euma
        pattern_type: cone
        # pattern_type: [0.1278, 0.1748, 0.2787, 0.3853, 0.2787, 0.1748, 0.1278]
        trigger_len: 4
        pattern_len: 7
        bef_tgr_len: 6
        lam_norm: 0.05
        alpha_s: 0.3  # spatial_poison_rate
        alpha_t: 0.03  # temporal_poison_rate
        epsilon: 0.2
        hidden_dim: 64  # hidden_dim for the trigger generator

    attack_contrib:
        # poison_number: [1,2,3,4,5,6,7,8,9,10] # num_values
        poison_number: [10,12]
        poison_length: 1
        epsilon: [0.1,0.05]
        # epsilon : [0.1]

    highest_contrib:
        # poison_number: [1,2,3,4,5,6,7,8,9,10] # num_values
        poison_number: [10,12]
        poison_length: 1
        epsilon: [0.1,0.05]

    attack_distrib:
        # poison_number: [1,2,3,4,5,6,7,8,9,10] # num_values
        poison_number: [10,12]
        poison_length: 1
        epsilon: [0.1,0.05]

    attack_rolling_var:
        epsilon: [0.1,0.05]
        # poison_number: [1,2,3,4,5,6,7,8,9,10] # quantile
        poison_number: [1,2]

    attack_rolling_var_dynamic:
        epsilon: [0.1,0.05]
        # poison_number: [1,2,3,4,5,6,7,8,9,10] # top_k_values
        poison_number: [1,3]
    fgsm:
        poison_number: [0] # Only put one value for avoiding errors but this field is useless
        epsilon: [0.1,0.05]
    bim:
        poison_number: [10,20,30,40,50,60,70,80,90,100]
        epsilon: [0.1,0.05]
    pgd:
        poison_number: [10,20,30,40,50,60,70,80,90,100]
        epsilon: [0.1,0.05]

Target_Pattern:
    cone: [0.1278, 0.1748, 0.2787, 0.3853, 0.2787, 0.1748, 0.1278]
    up_trend: [0.1405, 0.2064, 0.2705, 0.2835, 0.2949, 0.3495, 0.3567]
    up_and_down: [0.10, 0.1687, 0.2851, 0.09601, -0.0230, -0.0916, -0.2402]